version: "3"

services:
  vsftpd:
    image: hydrohs/vsftpd
    restart: unless-stopped
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./home:/home/vsftpd
      - ./logs:/var/log/vsftpd
      - ./cert:/etc/vsftpd/cert
