version: "3"

services:
  vsftpd:
    #image: XXXX -- change to image whenever built.
    build:
      context: .
    #restart: unless-stopped
    ports:
      - "20:20"
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./ftp:/home/ftp
      - ./etc/cert:/etc/vsftpd/cert
      - ./etc/users/:/etc/vsftpd/users/
      - ./logs:/var/log/vsftpd/
    environment:
      - FTP_USER=admin
      - FTP_PASS=admin
#      - PAM_DSN=host=db port=5432 dbname=postgres user=postgres password=postgres connect_timeout=15
      - SSL_ENABLE=YES
      - TLS_CERT=vsftpd.crt
      - TLS_KEY=vsftpd.key
      - LOG_STDOUT=yes
